name: Create Tag and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create-tag-and-release:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        if: ${{ github.event_name != 'pull_request' }}
        continue-on-error: false
        uses: mathieudutour/github-tag-action@v6.1
        with:
          tag_prefix: ''
          github_token: ${{ secrets.PAT }}

      - name: Create a GitHub release
        if: ${{ github.event_name != 'pull_request' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.PAT }}